version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:

  build_storybook:
    docker:
      - image: cimg/node:16.6 # the primary container, where your job's commands are run

    steps:
      - checkout # check out the code in the project directory
      - node/install-packages
      - attach_workspace:
          at: ~/NativeBaseComponentLibrary
      - run: npm run build-storybook
      - persist_to_workspace:
          root: ~/NativeBaseComponentLibrary
          paths:
            - .
  
workflows:
  Build and Deploy Component Library:
    jobs:
      - build_storybook
      - release:
          requires:
            - build_storybook
          filters:
            branches:
              only:
                - main